language: php
sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/composer
        - $HOME/.composer
        - $HOME/.composer/cache/files
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit

matrix:
    fast_finish: true
    include:
    - php: 7.1
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.1.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.2.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.3.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.1.*"

before_install:
- if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
- if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit
